// next/journey/src/app/components/features/Calendar.tsx
import React, { useState } from "react";
import * as datefns from "date-fns";
import { CaretLeft, CaretRight } from "@phosphor-icons/react";

const Calendar = () => {
    const [date, setDate] = useState(new Date());

    const currentDay = () => datefns.format(date, "d");
    const currentMonth = () => datefns.format(date, "MMMM");
    const currentYear = () => datefns.format(date, "yyyy");

    const previousMonth = () => {
        setDate(datefns.subMonths(date, 1));
    };
    const nextMonth = () => {
        setDate(datefns.addMonths(date, 1));
    };

    const goToToday = () => {
        setDate(new Date());
    };

    const calendarDays = () => [...Array(datefns.getDaysInMonth(date)).keys()];
    const calendarDates = () => calendarDays().map((day) => day + 1);

    const isToday = (day) => {
        const today = new Date();
        return (
            datefns.isSameDay(date, today) &&
            datefns.isSameMonth(date, today) &&
            datefns.isSameYear(date, today) &&
            day === datefns.getDate(today)
        );
    };

    const daysOfWeek = () => ["S", "M", "T", "W", "T", "F", "S"];

    return (
        <div className=" bg-zinc-800 p-3 rounded-md">
            <div className="flex justify-between p-2">
                <button onClick={previousMonth}><CaretLeft/></button>
                <span className="text-2xl font-bold text-center">{currentMonth()}</span>
                <button onClick={nextMonth}><CaretRight/></button>
            </div>
            <div className="grid grid-cols-7 font-bold">
                {daysOfWeek().map((dayOfWeek) => (
                    <div className="flex content-center justify-center p-2" key={dayOfWeek}>
                        {dayOfWeek}
                    </div>
                ))}
            </div>
            <div className="grid grid-cols-7">
                {calendarDates().map((calendarDate) => (
                    <div
                        className={`flex content-center justify-center p-2 ${
                            isToday(calendarDate) ? "bg-zinc-600 font-bold rounded-md" : ""
                        }`}
                        key={calendarDate}
                    >
                        {calendarDate}
                    </div>
                ))}
            </div>
        </div>
    );
};

export default Calendar;

// vue/journey/components/calendar.vue
<template>
    <div class="calendar">
        <div class="day__header">
            <div class="day__header__item" v-for="day in daysOfWeek()" :key="day">
                {{ day }}
            </div>
        </div>
        <div class="day__body">
            <div class="day__body__item" v-for="day in calendarDates()" :key="day"
                :class="{ 'day__body__item--today': isToday(day) }">
                {{ day }}
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import * as datefns from "date-fns";

const date = ref(new Date());

const currentDay = () => datefns.format(date.value, "d");
const currentMonth = () => datefns.format(date.value, "MMMM");
const currentYear = () => datefns.format(date.value, "yyyy");

const previousMonth = () => {
    date.value = datefns.subMonths(date.value, 1);
};
const nextMonth = () => {
    date.value = datefns.addMonths(date.value, 1);
};

const goToToday = () => {
    date.value = new Date();
};

const calendarDays = () => [...Array(datefns.getDaysInMonth(date.value)).keys()];
const calendarDates = () => calendarDays().map((day) => day + 1);

const isToday = (day: number) => {
    const today = new Date();
    return (
        datefns.isSameDay(date.value, today) &&
        datefns.isSameMonth(date.value, today) &&
        datefns.isSameYear(date.value, today) &&
        day === datefns.getDate(today)
    );
};

const daysOfWeek = () => [
    "S",
    "M",
    "T",
    "W",
    "T",
    "F",
    "S",
];
</script>

<style scoped>
.calendar {
    display: flex;
    flex-direction: column;
    width: 100%;
    border: 1px solid #e0e0e0;
}

.day__header {
    background-color: #f5f5f5;
    font-weight: bold;
    border-bottom: 1px solid #e0e0e0;
}

.day__header, .day__body {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
}

.day__header__item, .day__body__item {
    display: flex;
    justify-content: center;
    align-items: center;
    aspect-ratio: 1;
}

.day__body__item--today {
    background-color: #f0f0f0;
    border-radius: 1rem;
    margin: 0.5rem;
    font-weight: bold;
}


</style>
